version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:<< parameters.python >>
    working_directory: ~/django-post-request-task
    parameters:
      python:
        type: string
      django:
        type: string
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: tox python=<< parameters.python >> django=<< parameters.django >>
          command: tox -e "py$(echo '<< parameters.python >>' | tr -d '.')-django<< parameters.django >>"

workflows:
  default-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              python: ["3.8", "3.9", "3.10"]
              django: ["32", "40"]
